services:
  sql-poc:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-poc
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "LiquibasePOC!2026"
    ports:
      - "1433:1433"
    volumes:
      - sql-poc-data:/var/opt/mssql

volumes:
  sql-poc-data:
