# Liquibase connection properties for NICE POC
# Fill in the values below then run: liquibase update

changeLogFile=changelog/db.changelog-main.xml
searchPath=.

# SQL Server JDBC URL format:
# jdbc:sqlserver://<host>:<port>;databaseName=<db_name>;encrypt=true;trustServerCertificate=true
# Enable Liquibase change log history
liquibase.dbclhistory.enabled=true 
liquibase.dbclhistory.file=liquibase.dbclhistory  
liquibase.diff.ignoreDefaultValueConstraintNames=true

# Logging
liquibase.logFormat=JSON
liquibase.logFile=liquibase.json
liquibase.logLevel=INFO
liquibase.command.checksScriptsEnabled=true