-- liquibase formatted sql

-- changeset benriley:1788772310925-1 splitStatements:false
CREATE TABLE "demo5" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), CONSTRAINT "demo5_pkey" PRIMARY KEY ("id"));

-- changeset benriley:1788772310925-2 splitStatements:false
CREATE TABLE "demo4" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), CONSTRAINT "demo4_pkey" PRIMARY KEY ("id"));

-- changeset benriley:1788772310925-3 splitStatements:false
CREATE TABLE "demo3" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), CONSTRAINT "demo3_pkey" PRIMARY KEY ("id"));

-- changeset benriley:1788772310925-4 splitStatements:false
CREATE TABLE "demo2" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), CONSTRAINT "demo2_pkey" PRIMARY KEY ("id"));

-- changeset benriley:1788772310925-5 splitStatements:false
CREATE TABLE "demo1" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR(100), CONSTRAINT "demo1_pkey" PRIMARY KEY ("id"));

-- changeset benriley:1788772310925-6 splitStatements:false
CREATE TABLE "employees" ("employee_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, "first_name" VARCHAR(100) NOT NULL, "last_name" VARCHAR(100) NOT NULL, "email" VARCHAR(255) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL, "is_active" BOOLEAN DEFAULT TRUE NOT NULL, CONSTRAINT "pk_employees" PRIMARY KEY ("employee_id"));

-- changeset benriley:1788772310925-7 splitStatements:false
ALTER TABLE "employees" ADD CONSTRAINT "uq_employees_email" UNIQUE ("email");

